import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import LivePreviewProvider from "@/context/LivePreviewProvider";
import { MenuContextProvider } from "@/context/menuContextProvider";
import type { Metadata } from "next";
import { Inter, Questrial } from "next/font/google";
import { draftMode } from "next/headers";
import Script from "next/script";
import "./globals.css";

const rowdies = Questrial({
  variable: "--font-rowdies",
  subsets: ["latin"],
  weight: ["400"],
});

const sans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["500", "700", "800"],
});

export const metadata: Metadata = {
  title: "Mormor och jag",
  description: "Generated by Alexander&Son",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isEnabled } = await draftMode();

  return (
    <html
      lang="en"
      className={`${sans.variable} ${rowdies.variable} antialiased`}
    >
      <body>
        <MenuContextProvider>
          <LivePreviewProvider isEnabled={isEnabled}>
            <Navbar />
            {children}
            <Footer />
          </LivePreviewProvider>
        </MenuContextProvider>
      </body>
      {isEnabled && <Script src="/live-preview.mjs" />}
    </html>
  );
}
