import { Footer, Navbar } from "@/components";
import type { Metadata } from "next";
import { Inter, Questrial } from "next/font/google";
import "./globals.css";

const rowdies = Questrial({
  variable: "--font-rowdies",
  subsets: ["latin"],
  weight: ["400"],
});

const sans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["500", "700", "800"],
});

export const metadata: Metadata = {
  title: "Mormor och jag",
  description: "Generated by Alexander&Son",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sans.variable} ${rowdies.variable} antialiased`}
    >
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
